### ISSUE TITLE
Bug in Traversables exercies.

### ISSUE THREAD

**Issue by bAmrish** [scala-exercises/exercises-stdlib#100]
There seems to be a bug in the Traversables exercises:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/419340/33887523-00cd1412-df70-11e7-9ef6-6831b01080b5.png">

Also this assertion seems to be non-deterministic: `(totalReduceRightTime > totalReduceLeftTime) should be()` 
Locally I have tried to run this multiple times and I have varied results. Something to consider when updating this exercise.

**Comment by FRosner** [comment]
Thanks @bAmrish for reporting this. We already fixed it in #97. The new exercise should be available in the next days.

Does it make sense to you?

**Comment by bAmrish** [comment]
Thanks @FRosner! Just looked at the change, I agree with your comments. I am glad you are removing the non-deterministic behavior!
