### ISSUE TITLE
Options section error

### ISSUE THREAD

**Issue by idarlington** [scala-exercises/exercises-stdlib#13]
Hi, 

``` scala
def matchOptions(res0: Float, res1: Float) {
    val someValue: Option[Double] = Some(20.0)
    val value = someValue match {
      case Some(v) ⇒ v
      case None    ⇒ 0.0
    }
    value should be(res0)
    val noValue: Option[Double] = None
    val value1 = noValue match {
      case Some(v) ⇒ v
      case None    ⇒ 0.0
    }
    value1 should be(res1)
  }
```

The above test in the options exercise throws an error because the test is comparing a **Float** to a **Double** ` value1 should be(res1)` and most persons input their answers as Double. 

I could put in a pull request.

**Comment by raulraja** [comment]
@idarlington makes sense. Would love to see a PR thanks!

**Comment by idarlington** [comment]
Hi @raulraja  what is the PR process like.

**Comment by raulraja** [comment]
@idarlington Just fork this repo, make any changes in your repo, push and send a PR back when ready. We can give you push access down the road if you plan on contributing more. Thanks!

**Comment by idarlington** [comment]
@raulraja  I have done that. Thanks. 

I am also interested in contributing more moving forward.
