### ISSUE TITLE
Bug in last exercise of Partially Applied Functions

### ISSUE THREAD

**Issue by genghis-yang** [scala-exercises/exercises-stdlib#132]
It says **"There was a problem evaluating your answer, please try again later."** in the last exercise in Partially Applied Functions even when I can run it successfully in local Scala console.

It seems the operator **"=>"** was converted to a character **'⇒'** exceptionally. 

I have submitted a PR #131 to fix it. Please check and merge it.

**Comment by atisvagyok** [comment]
The Unicode form of "Rightwards Double Arrow" is a valid keyword. You can check it in spec. (https://scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html#identifiers)

> The Unicode operators \u21D2 ‘⇒’ and \u2190 ‘←’, which have the ASCII equivalents => and <-, are also reserved.

The Unicode and ASCII versions can be used interchangeably.

```
scala> def fun(g: Int ⇒ Boolean) = ???
fun: (g: Int => Boolean)Nothing

scala> def fun(g: Int => Boolean) = ???
fun: (g: Int => Boolean)Nothing
```

**Comment by genghis-yang** [comment]
> The Unicode form of "Rightwards Double Arrow" is a valid keyword. You can check it in spec. (https://scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html#identifiers)
> 
> > The Unicode operators \u21D2 ‘⇒’ and \u2190 ‘←’, which have the ASCII equivalents => and <-, are also reserved.
> 
> The Unicode and ASCII versions can be used interchangeably.
> 
> ```
> scala> def fun(g: Int ⇒ Boolean) = ???
> fun: (g: Int => Boolean)Nothing
> 
> scala> def fun(g: Int => Boolean) = ???
> fun: (g: Int => Boolean)Nothing
> ```

Thanks for your explanation. I will close this issue.
