### ISSUE TITLE
Lists - Lists reuse their tails

### ISSUE THREAD

**Issue by javierjmx2000** [scala-exercises/exercises-stdlib#141]
Why is this wrong?

![Screen Shot 2019-07-15 at 12 11 01 PM](https://user-images.githubusercontent.com/37085588/61234881-d0b37480-a6f9-11e9-96b7-c80cb3b83d75.png)

**Comment by AdrianRaFo** [comment]
I fear that `Nil` is not the same as `List()`

**Comment by javierjmx2000** [comment]
Neither `List()` or `Nil` are working. I also tried with `List[Int]()` and still wrong.

**Comment by AdrianRaFo** [comment]
Oh, I see now, on the first question you answered `List(1, 3, 3)` which I think it's a little typo isn't it?

**Comment by javierjmx2000** [comment]
OMG! Thank you @AdrianRaFo
