### ISSUE TITLE
Another case of Float

### ISSUE THREAD

**Issue by idarlington** [scala-exercises/exercises-stdlib#19]
Hi, so I noticed another case of the exercise expecting a **Float** instead of a **Double** 

**Tuple Section**
```  
def assignVariablesTuples(res0: String, res1: Int, res2: Float) {
    val student = ("Sean Rogers", 21, 3.5)
    val (name, age, gpa) = student

    name should be(res0)
    age should be(res1)
    gpa should be(res2)
  }
````

If the expected user input should be Floats, then it should probably be specified in the **readme** or in each exercise.

**Comment by raulraja** [comment]
No point for Floats, it's an oversight from we when ported the original Koans over. PRs welcome!

**Comment by idarlington** [comment]
Ok @raulraja  I would work on it.

**Comment by idarlington** [comment]
Hi @raulraja  what repository is this dependency available in :
```
addSbtPlugin("org.scala-exercises" % "sbt-exercise" % "0.0.0-SNAPSHOT", "0.13", "2.10")
```

Do I have to publish it locally ?

**Comment by raulraja** [comment]
It's in the scala-exercises repo under a submodule. There is a script to
publish all dependencies locally

**Comment by idarlington** [comment]
@raulraja  you mean this [repo](https://github.com/scala-exercises/scala-exercises) ?

I can't seem to find the script that publishes dependencies.

**Comment by raulraja** [comment]
It's a sbt command alias `sbt publishAll` https://github.com/scala-exercises/scala-exercises/blob/master/build.sbt#L294

**Comment by idarlington** [comment]
Ok, I thought you meant a bash script.  
So for the other question is it the repo i linked to?

**Comment by raulraja** [comment]
Yes it's the same repo as the site that contains the compiler and sbt
plugin

**Comment by idarlington** [comment]
Hi @raulraja, I get this error when compiling, I think it has to do with Github Authentication

```
[info] Fetching contributions for repository scala-exercises/exercises-stdlib file /src/main/scala/stdlib/Asserts.scala
github4s.GithubResponses$UnexpectedException: Failed invoking get with status : 403, body : 
 {"message":"API rate limit exceeded for 197.242.97.177. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Comment by dialelo** [comment]
@idarlington as mentioned in the README, you'll want to set the `GITHUB_TOKEN` environment variable for not hitting the GitHub API's rate limit. You can [obtain a token here](https://github.com/settings/tokens/new).

**Comment by raulraja** [comment]
@idarlington feel free to reopen this if the issue continues after using your own` GITHUB_TOKEN`

**Comment by idarlington** [comment]
@raulraja no problem, I resolved this with @rafaparadela in the gitter channel. Thanks.
