### ISSUE TITLE
Misrepresented question

### ISSUE THREAD

**Issue by idarlington** [scala-exercises/exercises-stdlib#30]
In the Lists exercise, the question is this :  
```scala 
a.filter(_ % 2 != 0) should equal(List(  ? , ?  ))
```
but the code has this and the test is suited to it.
```scala
  a.filter {
      _ % 2 == 0
    } should equal(List(res3))
```

**Comment by idarlington** [comment]
@raulraja  what do you think?

**Comment by dialelo** [comment]
Hmm i fail to see the problem here, i believe the two exercises you are referring to are separate exercises:

![lists](https://cloud.githubusercontent.com/assets/409039/16408166/ad7c9982-3d17-11e6-8445-835e16bc9c02.png)

**Comment by idarlington** [comment]
Sure, just realised, my bad.

**Comment by dialelo** [comment]
No problem, thanks for your time!
