### ISSUE TITLE
Bullet list doesn't work proper in sets page

### ISSUE THREAD

**Issue by hyunjun** [scala-exercises/exercises-stdlib#55]
https://www.scala-exercises.org/std_lib/sets
![2016-09-26 11 04 26](https://cloud.githubusercontent.com/assets/248764/18820469/0904aa08-83d9-11e6-8d6c-bc1568d45f1a.png)

**Comment by aseigneurin** [comment]
+1

**Comment by aseigneurin** [comment]
I would even say that Markdown is not interpreted: lists, bold, italic.
